export const translations = {
  EN: {
    nav: { services: "Services", audience: "Audience", testimonials: "Testimonials", pricing: "Pricing", urgency: "Reason to Take", getInTouch: "GET IN TOUCH" },
    hero: { getYour: "GET YOUR", digitalAvatar: "DIGITAL AVATAR", now: "NOW!!!", sub: "DIGITAL AI AVATARS THAT CAMPAIGN FOR YOU 24/7. CONNECT WITH CONSTITUENTS PERSONALLY, AT SCALE.", cta: "SEE HOW IT WORKS" },
    marquee: { m1: "🚀 BE EVERYWHERE AT ONCE", m2: "⚡ 10X YOUR OUTREACH", m3: "🔥 PERSONALIZE AT SCALE", m4: "🤖 THE FUTURE IS HERE" },
    services: { title: "WHAT WE DO", s1_title: "CLONE YOUR VOICE & FACE", s1_desc: "UPLOAD ONCE. GENERATE THOUSANDS OF VIDEOS IN SECONDS.", s2_title: "HYPER-PERSONALIZATION", s2_desc: "CALL VOTERS BY THEIR NAME IN THEIR LOCAL DIALECT.", s3_title: "WHATSAPP INTEGRATION", s3_desc: "DIRECT TO THEIR PHONES. 98% OPEN RATE." },
    audience: { title1: "BUILT FOR", title2: "LEADERS", sub: "ENGINEERED EXCLUSIVELY FOR GRASSROOTS LEADERS WHO NEED IMPACT.", a1: "CORPORATORS", a2: "MLAS", a3: "PARTY REPS", a4: "COUNCIL MEMBERS" },
    testi: { title: "TESTIMONIALS /", title2: "EXPECTED OUTPUTS", v1_title: "AI-GENERATED CAMPAIGN MESSAGE", v1_sub: "EXACT VOICE & FACE CLONING", v2_title: "PERSONALIZED VOTER OUTREACH", v2_sub: "SEAMLESS REGIONAL DELIVERY" },
    adv: { title: "THE AIxPOLITICS ADVANTAGE", p1_t: "Personalised outreach that leaves a lasting impression", p1_d: "Your message reaches people in a way they won’t forget.", p2_t: "Exact face & voice cloning", p2_d: "We create highly realistic videos using advanced AI face and voice cloning technology.", p2_i: "(The sample videos shown above are for illustration purposes only.)", p3_t: "Videos up to 1 minute", p3_d: "Short, impactful clips tailored to your needs.", p4_t: "Clean, professional delivery", p4_d: "Sample videos may carry watermarks. Your final videos will be delivered completely watermark-free.", p5_t: "Be present without being present", p5_d: "No need to shoot new footage. Stay visible, save time, and scale your outreach effortlessly." },
    pricing: { title: "PRICING_TIERS", att_t: "ATTENTION", att_p1: "ALL PLANS REQUIRE A ONE-TIME", att_fee: "₹2 LAKHS SETUP FEE", att_p2: "FOR AVATAR GENERATION", mo: "/MO", 
               b_title: "BASIC", b_sub: "ENTRY LEVEL", b_btn: "SELECT BASIC", b_f1: "STANDARD AVATAR", b_f2: "1,000 MINS PERSONALISED VIDEOS", b_f3: "EMAIL SUPPORT", b_f4: "3 SPECIAL HEAVY AI VIDEOS",
               p_tag: "MOST POPULAR", p_title: "PRO", p_sub: "REGIONAL REPS", p_btn: "SELECT PRO", p_f1: "PREMIUM AVATAR", p_f2: "3,000 MINS PERSONALISED VIDEOS", p_f3: "WHATSAPP SHAREABLE", p_f4: "10 SPECIAL HEAVY AI VIDEOS", p_f5: "ANALYTICS",
               c_title: "PARTY", c_sub: "ENTERPRISE", c_price: "TALK 2 US", c_btn: "CONTACT SALES", c_f1: "UNLIMITED VIDEOS", c_f2: "MULTIPLE AVATARS", c_f3: "ON-SITE SETUP" },
    fomo: { title: "SURVIVAL OF THE", strike: "FITTEST", fast: "FASTEST", hook: "YOUR OPPONENT IS LOOKING AT THIS EXACT SAME TECHNOLOGY.", sub: "In politics, the first to adopt breakthrough technology controls the narrative. The second simply reacts. While you hesitate, someone else is securing the ultimate unfair advantage.", m_title: "FIRST-MOVER MONOPOLY", m_desc: "Voters remember the candidate who reached them first, in their own language, calling them by name. That level of shock and awe cannot be replicated twice.", b_title: "LIMITED BANDWIDTH", b_desc: "Training high-fidelity AI avatars requires massive computing power. We have a strict cap on the number of candidates we onboard before the next election cycle." },
    contact: { title: "INITIATE", title2: "CONTACT", sub: "READY TO DOMINATE YOUR NEXT ELECTION? TRANSMIT A SIGNAL.", email: "CLICK TO EMAIL", phone: "CLICK TO CALL" }
  },
  TE: {
    nav: { services: "సేవలు", audience: "ప్రేక్షకులు", testimonials: "ప్రశంసలు", pricing: "ధరలు", urgency: "ఎందుకు తీసుకోవాలి", getInTouch: "సంప్రదించండి" },
    hero: { getYour: "పొందండి మీ", digitalAvatar: "డిజిటల్ అవతార్", now: "ఇప్పుడే!!!", sub: "మీ కోసం 24/7 ప్రచారం చేసే డిజిటల్ AI అవతార్లు. నియోజకవర్గ ప్రజలతో వ్యక్తిగతంగా కనెక్ట్ అవ్వండి.", cta: "ఎలా పనిచేస్తుందో చూడండి" },
    marquee: { m1: "🚀 ఒకేసారి ప్రతి చోటా ఉండండి", m2: "⚡ మీ చేరువను 10X పెంచుకోండి", m3: "🔥 భారీ స్థాయిలో వ్యక్తిగతీకరణ", m4: "🤖 భవిష్యత్తు ఇక్కడే ఉంది" },
    services: { title: "మేము ఏమి చేస్తాము", s1_title: "మీ వాయిస్ & ముఖాన్ని క్లోన్ చేయండి", s1_desc: "ఒక్కసారి అప్‌లోడ్ చేయండి. క్షణాల్లో వేలాది వీడియోలను సృష్టించండి.", s2_title: "హైపర్-పర్సనలైజేషన్", s2_desc: "ఓటర్లను వారి పేరుతో వారి స్థానిక మాండలికంలో పిలవండి.", s3_title: "వాట్సాప్ అనుసంధానం", s3_desc: "నేరుగా వారి ఫోన్లకు. 98% ఓపెన్ రేట్." },
    audience: { title1: "నాయకుల కోసం", title2: "రూపొందించబడింది", sub: "ప్రభావం చూపాలనుకునే అట్టడుగు స్థాయి నాయకుల కోసం ప్రత్యేకంగా రూపొందించబడింది.", a1: "కార్పొరేటర్లు", a2: "ఎమ్మెల్యేలు", a3: "పార్టీ ప్రతినిధులు", a4: "కౌన్సిల్ సభ్యులు" },
    testi: { title: "ప్రశంసలు /", title2: "ఆశించిన ఫలితాలు", v1_title: "AI సృష్టించిన ప్రచార సందేశం", v1_sub: "ఖచ్చితమైన వాయిస్ & ముఖ క్లోనింగ్", v2_title: "వ్యక్తిగతీకరించిన ఓటర్ల చేరువ", v2_sub: "అతుకులు లేని ప్రాంతీయ బట్వాడా" },
    adv: { title: "AIxPOLITICS అడ్వాంటేజ్", p1_t: "మరచిపోలేని వ్యక్తిగతీకరించిన చేరువ", p1_d: "మీ సందేశం ప్రజలకు వారు ఎప్పటికీ మరచిపోలేని విధంగా చేరుతుంది.", p2_t: "ఖచ్చితమైన ముఖం & వాయిస్ క్లోనింగ్", p2_d: "అధునాతన AI సాంకేతికతను ఉపయోగించి మేము అత్యంత వాస్తవిక వీడియోలను సృష్టిస్తాము.", p2_i: "(పైన చూపించిన నమూనా వీడియోలు ఉదాహరణకు మాత్రమే.)", p3_t: "1 నిమిషం వరకు వీడియోలు", p3_d: "మీ అవసరాలకు తగినట్లుగా చిన్న, ప్రభావవంతమైన క్లిప్‌లు.", p4_t: "క్లీన్, ప్రొఫెషనల్ డెలివరీ", p4_d: "నమూనా వీడియోలలో వాటర్‌మార్క్‌లు ఉండవచ్చు. మీ తుది వీడియోలు వాటర్‌మార్క్ లేకుండా డెలివరీ చేయబడతాయి.", p5_t: "ఉండకుండానే ఉండండి", p5_d: "కొత్త ఫుటేజ్ తీయాల్సిన అవసరం లేదు. సమయం ఆదా చేసుకోండి." },
    pricing: { title: "ధరల పట్టిక", att_t: "శ్రద్ధ వహించండి", att_p1: "అన్ని ప్లాన్‌లకు ఒకే సారి", att_fee: "₹2 లక్షల సెటప్ ఫీజు", att_p2: "అవతార్ సృష్టికి అవసరం", mo: "/నెల", 
               b_title: "బేసిక్", b_sub: "ఎంట్రీ లెవెల్", b_btn: "బేసిక్ ఎంచుకోండి", b_f1: "స్టాండర్డ్ అవతార్", b_f2: "1,000 నిమిషాల వ్యక్తిగతీకరించిన వీడియోలు", b_f3: "ఈమెయిల్ సపోర్ట్", b_f4: "3 ప్రత్యేక హెవీ AI వీడియోలు",
               p_tag: "అత్యంత ప్రజాదరణ", p_title: "ప్రో", p_sub: "ప్రాంతీయ ప్రతినిధులు", p_btn: "ప్రో ఎంచుకోండి", p_f1: "ప్రీమియం అవతార్", p_f2: "3,000 నిమిషాల వ్యక్తిగతీకరించిన వీడియోలు", p_f3: "వాట్సాప్‌లో షేర్ చేయవచ్చు", p_f4: "10 ప్రత్యేక హెవీ AI వీడియోలు", p_f5: "అనలిటిక్స్",
               c_title: "పార్టీ", c_sub: "ఎంటర్‌ప్రైజ్", c_price: "మాతో మాట్లాడండి", c_btn: "సేల్స్‌ని సంప్రదించండి", c_f1: "అపరిమిత వీడియోలు", c_f2: "బహుళ అవతార్లు", c_f3: "ఆన్-సైట్ సెటప్" },
    fomo: { title: "వేగంగా ఉన్నవారిదే", strike: "గెలుపు", fast: "రాజ్యం", hook: "మీ ప్రత్యర్థి సరిగ్గా ఇదే టెక్నాలజీని చూస్తున్నాడు.", sub: "రాజకీయాల్లో, కొత్త టెక్నాలజీని ముందుగా వాడేవారే కథను శాసిస్తారు. రెండో వారు కేవలం స్పందిస్తారు. మీరు ఆలోచించేలోపు, ఇంకెవరో ఆధిక్యం సాధిస్తున్నారు.", m_title: "ఫస్ట్-మూవర్ మోనోపోలీ", m_desc: "తమ సొంత భాషలో, పేరు పెట్టి పిలిచి ముందుగా చేరువైన నాయకుడినే ఓటర్లు గుర్తుపెట్టుకుంటారు.", b_title: "పరిమిత సామర్థ్యం", b_desc: "హై-ఫిడిలిటీ AI అవతార్‌లకు భారీ కంప్యూటింగ్ శక్తి అవసరం. తదుపరి ఎన్నికలకు ముందు పరిమిత సంఖ్యలో మాత్రమే చేర్చుకుంటాము." },
    contact: { title: "సంప్రదించడం", title2: "ప్రారంభించండి", sub: "మీ తదుపరి ఎన్నికల్లో ఆధిపత్యం చెలాయించడానికి సిద్ధమా? సిగ్నల్ పంపండి.", email: "ఈమెయిల్ కోసం క్లిక్ చేయండి", phone: "కాల్ చేయడానికి క్లిక్ చేయండి" }
  },
  HI: {
    nav: { services: "सेवाएं", audience: "दर्शक", testimonials: "प्रशंसापत्र", pricing: "कीमतें", urgency: "क्यों चुनें", getInTouch: "संपर्क करें" },
    hero: { getYour: "पाएं अपना", digitalAvatar: "डिजिटल अवतार", now: "अभी!!!", sub: "डिजिटल AI अवतार जो आपके लिए 24/7 प्रचार करते हैं। मतदाताओं से व्यक्तिगत रूप से जुड़ें, बड़े पैमाने पर।", cta: "देखें यह कैसे काम करता है" },
    marquee: { m1: "🚀 एक ही समय में हर जगह रहें", m2: "⚡ अपनी पहुँच को 10X बढ़ाएं", m3: "🔥 बड़े पैमाने पर निजीकरण", m4: "🤖 भविष्य यहाँ है" },
    services: { title: "हम क्या करते हैं", s1_title: "अपनी आवाज़ और चेहरा क्लोन करें", s1_desc: "एक बार अपलोड करें। सेकंडों में हजारों वीडियो बनाएं।", s2_title: "हाइपर-पर्सनलाइज़ेशन", s2_desc: "मतदाताओं को उनकी स्थानीय बोली में उनके नाम से पुकारें।", s3_title: "व्हाट्सएप एकीकरण", s3_desc: "सीधे उनके फोन पर। 98% ओपन रेट।" },
    audience: { title1: "नेताओं के लिए", title2: "निर्मित", sub: "प्रभाव की आवश्यकता वाले जमीनी स्तर के नेताओं के लिए विशेष रूप से इंजीनियर किया गया।", a1: "पार्षद", a2: "विधायक", a3: "पार्टी प्रतिनिधि", a4: "परिषद सदस्य" },
    testi: { title: "प्रशंसापत्र /", title2: "अपेक्षित परिणाम", v1_title: "AI-जनरेटेड अभियान संदेश", v1_sub: "सटीक आवाज़ और चेहरा क्लोनिंग", v2_title: "व्यक्तिगत मतदाता संपर्क", v2_sub: "निर्बाध क्षेत्रीय वितरण" },
    adv: { title: "AIxPOLITICS लाभ", p1_t: "व्यक्तिगत संपर्क जो अमिट छाप छोड़ता है", p1_d: "आपका संदेश लोगों तक इस तरह पहुँचता है जिसे वे कभी नहीं भूलेंगे।", p2_t: "सटीक चेहरा और आवाज़ क्लोनिंग", p2_d: "हम उन्नत AI तकनीक का उपयोग करके अत्यधिक यथार्थवादी वीडियो बनाते हैं।", p2_i: "(ऊपर दिखाए गए नमूना वीडियो केवल चित्रण के लिए हैं।)", p3_t: "1 मिनट तक के वीडियो", p3_d: "आपकी आवश्यकताओं के अनुरूप छोटे, प्रभावशाली क्लिप।", p4_t: "क्लीन, पेशेवर डिलीवरी", p4_d: "नमूना वीडियो में वॉटरमार्क हो सकते हैं। आपके अंतिम वीडियो वॉटरमार्क-मुक्त होंगे।", p5_t: "उपस्थित हुए बिना उपस्थित रहें", p5_d: "नए फुटेज शूट करने की आवश्यकता नहीं है। समय बचाएं।" },
    pricing: { title: "मूल्य निर्धारण", att_t: "ध्यान दें", att_p1: "सभी योजनाओं के लिए एक बार", att_fee: "₹2 लाख सेटअप शुल्क", att_p2: "अवतार जनरेशन के लिए आवश्यक है", mo: "/माह", 
               b_title: "बेसिक", b_sub: "एंट्री लेवल", b_btn: "बेसिक चुनें", b_f1: "स्टैंडर्ड अवतार", b_f2: "1,000 मिनट व्यक्तिगत वीडियो", b_f3: "ईमेल सपोर्ट", b_f4: "3 विशेष हेवी AI वीडियो",
               p_tag: "सबसे लोकप्रिय", p_title: "प्रो", p_sub: "क्षेत्रीय प्रतिनिधि", p_btn: "प्रो चुनें", p_f1: "प्रीमियम अवतार", p_f2: "3,000 मिनट व्यक्तिगत वीडियो", p_f3: "व्हाट्सएप पर शेयर करने योग्य", p_f4: "10 विशेष हेवी AI वीडियो", p_f5: "एनालिटिक्स",
               c_title: "पार्टी", c_sub: "एंटरप्राइज़", c_price: "हमसे बात करें", c_btn: "सेल्स से संपर्क करें", c_f1: "असीमित वीडियो", c_f2: "एकाधिक अवतार", c_f3: "ऑन-साइट सेटअप" },
    fomo: { title: "सबसे तेज़ की", strike: "जीत", fast: "सत्ता", hook: "आपका प्रतिद्वंद्वी ठीक यही तकनीक देख रहा है।", sub: "राजनीति में, जो नई तकनीक को पहले अपनाता है वह नैरेटिव को नियंत्रित करता है। दूसरा केवल प्रतिक्रिया करता है।", m_title: "फर्स्ट-मूवर मोनोपोली", m_desc: "मतदाता उस उम्मीदवार को याद रखते हैं जो उनके पास सबसे पहले, उनकी अपनी भाषा में, नाम लेकर पहुँचा।", b_title: "सीमित बैंडविड्थ", b_desc: "हाई-फिडेलिटी AI अवतारों को बड़े पैमाने पर कंप्यूटिंग पावर की आवश्यकता होती है। अगले चुनाव से पहले हमारे पास एक सख्त सीमा है।" },
    contact: { title: "संपर्क", title2: "शुरू करें", sub: "अपने अगले चुनाव में हावी होने के लिए तैयार हैं? एक संकेत भेजें।", email: "ईमेल के लिए क्लिक करें", phone: "कॉल करने के लिए क्लिक करें" }
  }
};
